baseURL = 'https://tanayjha-blog.vercel.app/'
languageCode = 'en-us'
title = 'My Musings'
theme = "PaperMod"

[params.profileMode]
enabled = true
title = 'My Tryst With CS'
subtitle = "My journey as a software developer"
imageUrl = "images/blogpic.jpeg"
imageTitle = "Me"
imageWidth = 120
imageHeight = 120

[[params.profileMode.buttons]]
  name = "Blog"
  url = "/blog"